import requests
from requests.auth import HTTPBasicAuth
import uuid

BASE_URL = "http://localhost:3000"
AUTH = HTTPBasicAuth("hexac64930@gmail.com", "Test.123")
HEADERS = {"Content-Type": "application/json"}
TIMEOUT = 30

def test_document_management_with_rich_text_editor_and_ai_assistance():
    doc_id = None
    try:
        # Step 1: Create a new document with rich text contents including headings, lists, code blocks, and inline AI command
        new_doc_payload = {
            "title": "Test Document with Rich Text Editor and AI Assistance",
            "content": {
                "type": "doc",
                "content": [
                    {"type": "heading", "attrs": {"level": 1}, "content": [{"type": "text", "text": "Heading Level 1"}]},
                    {"type": "paragraph", "content": [{"type": "text", "text": "This is a paragraph with some "}]},
                    {"type": "bullet_list", "content": [
                        {"type": "list_item", "content": [{"type": "text", "text": "Bullet item 1"}]},
                        {"type": "list_item", "content": [{"type": "text", "text": "Bullet item 2"}]}
                    ]},
                    {"type": "code_block", "content": [{"type": "text", "text": "print('Hello, AI!')"}]},
                    {"type": "paragraph", "content": [
                        {"type": "text", "text": "Inline AI Writing Command: "},
                        {"type": "ai_command", "attrs": {"command": "/expand"}, "content": [{"type": "text", "text": "Expand this text"}]}
                    ]}
                ]
            },
            "autoSave": True
        }
        create_resp = requests.post(
            f"{BASE_URL}/api/docs",
            json=new_doc_payload,
            headers=HEADERS,
            auth=AUTH,
            timeout=TIMEOUT
        )
        assert create_resp.status_code == 201, f"Document creation failed: {create_resp.text}"
        doc_data = create_resp.json()
        assert "id" in doc_data, "Response missing document ID"
        doc_id = doc_data["id"]

        # Step 2: Edit the document - modify title and update content to simulate AI assistance output
        updated_content = new_doc_payload["content"]
        # Simulate AI expanded text appended at the ai_command location (inline AI writing command)
        # Find ai_command node and add AI-expanded text after it
        for node in updated_content["content"]:
            if node.get("type") == "paragraph":
                for i, child in enumerate(node.get("content", [])):
                    if child.get("type") == "ai_command" and child.get("attrs", {}).get("command") == "/expand":
                        # Insert expanded AI text after this node
                        ai_text = {"type": "text", "text": " with additional detailed explanation generated by AI."}
                        node["content"].insert(i+1, ai_text)
                        break

        updated_doc_payload = {
            "title": "Updated Test Document with AI Assistance",
            "content": updated_content,
            "autoSave": True
        }
        update_resp = requests.put(
            f"{BASE_URL}/api/docs/{doc_id}",
            json=updated_doc_payload,
            headers=HEADERS,
            auth=AUTH,
            timeout=TIMEOUT
        )
        assert update_resp.status_code == 200, f"Document update failed: {update_resp.text}"
        updated_data = update_resp.json()
        assert updated_data.get("title") == updated_doc_payload["title"], "Title update did not persist"
        assert "with additional detailed explanation generated by AI." in str(updated_data.get("content")), "AI expanded text not saved"

        # Step 3: Validate auto-save functionality by simulating repeated updates and checking updated_at timestamps
        timestamps = []
        for i in range(3):
            # Simulate minor change
            updated_doc_payload["content"]["content"].append(
                {"type": "paragraph", "content": [{"type": "text", "text": f"Auto-save test paragraph {i+1}."}]}
            )
            auto_save_resp = requests.put(
                f"{BASE_URL}/api/docs/{doc_id}",
                json=updated_doc_payload,
                headers=HEADERS,
                auth=AUTH,
                timeout=TIMEOUT
            )
            assert auto_save_resp.status_code == 200, f"Auto-save attempt {i+1} failed: {auto_save_resp.text}"
            resp_json = auto_save_resp.json()
            timestamps.append(resp_json.get("updatedAt") or resp_json.get("updated_at"))
            assert timestamps[-1] is not None, "Auto-save response missing updated timestamp"

        # Check timestamps are in ascending order (each update updates timestamp)
        assert all(earlier < later for earlier, later in zip(timestamps, timestamps[1:])), "Auto-save timestamps not increasing"

        # Step 4: Security tests - attempt SQL Injection and XSS in title and content fields
        malicious_payloads = [
            {"title": "'; DROP TABLE documents; --", "content": {"type": "doc", "content": []}},
            {"title": "Normal Title", "content": {"type": "doc", "content": [
                {"type": "paragraph", "content": [{"type": "text", "text": "<script>alert('xss')</script>"}]}
            ]}}
        ]
        for malicious in malicious_payloads:
            sec_resp = requests.put(
                f"{BASE_URL}/api/docs/{doc_id}",
                json=malicious,
                headers=HEADERS,
                auth=AUTH,
                timeout=TIMEOUT
            )
            # Expect server to sanitize inputs or reject it with 400/422
            assert sec_resp.status_code in {200, 400, 422}, f"Unexpected status code for security test: {sec_resp.status_code}"
            # If accepted, verify returned content is sanitized (no script tag)
            if sec_resp.status_code == 200:
                resp_json = sec_resp.json()
                # Basic check: no script tags in title or content text fields
                if "script" in resp_json.get("title","" ).lower():
                    raise AssertionError("XSS not sanitized in title")
                content_str = str(resp_json.get("content",{})).lower()
                if "<script>" in content_str or "</script>" in content_str:
                    raise AssertionError("XSS not sanitized in content")

        # Step 5: Fetch document and verify saved content includes rich text and AI assistance modifications
        get_resp = requests.get(
            f"{BASE_URL}/api/docs/{doc_id}",
            headers=HEADERS,
            auth=AUTH,
            timeout=TIMEOUT
        )
        assert get_resp.status_code == 200, f"Failed to retrieve document: {get_resp.text}"
        fetched_doc = get_resp.json()
        assert fetched_doc.get("title") == updated_doc_payload["title"], "Fetched document title mismatch"
        assert "Heading Level 1" in str(fetched_doc.get("content")), "Heading content missing"
        assert "Auto-save test paragraph 3." in str(fetched_doc.get("content")), "Auto-save paragraphs missing"
        assert "additional detailed explanation generated by AI." in str(fetched_doc.get("content")), "AI assistance content missing"

    finally:
        if doc_id:
            # Cleanup - delete the created document
            try:
                del_resp = requests.delete(
                    f"{BASE_URL}/api/docs/{doc_id}",
                    headers=HEADERS,
                    auth=AUTH,
                    timeout=TIMEOUT
                )
                assert del_resp.status_code in (200, 204), f"Document deletion failed: {del_resp.text}"
            except Exception:
                pass

test_document_management_with_rich_text_editor_and_ai_assistance()
